# Generated by Otto, do not edit manually.

provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region     = "${var.aws_region}"
}

# Main VPC that will contain everything.
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"

  enable_dns_support   = true
  enable_dns_hostnames = true

  tags { Name = "otto" }
}

# The public subnet is where resources connected to the internet will go
resource "aws_subnet" "public" {
    count                   = "${var.aws_availability_zone_count}"
    availability_zone       = "${element(split(",",lookup(var.aws_availability_zones, var.aws_region)),count.index)}"
    vpc_id                  = "${aws_vpc.main.id}"
    cidr_block              = "10.0.${count.index + 1}.0/24"
    map_public_ip_on_launch = true
    tags { Name = "public" }
}

# Internet accessible route table + gateway for the public subnet
resource "aws_internet_gateway" "public" {
  vpc_id = "${aws_vpc.main.id}"
}

resource "aws_route_table" "public" {
  count  = "${var.aws_availability_zone_count}"
  vpc_id = "${aws_vpc.main.id}"
  route {
      cidr_block = "0.0.0.0/0"
      gateway_id = "${aws_internet_gateway.public.id}"
  }
  tags { Name = "public" }
}

resource "aws_route_table_association" "public" {
  count  = "${var.aws_availability_zone_count}"
  subnet_id      = "${element(aws_subnet.public.*.id, count.index)}"
  route_table_id = "${element(aws_route_table.public.*.id, count.index)}"
}

# SSH key that app implementations can use to grant SSH access to instances
resource "aws_key_pair" "main" {
  key_name   = "otto-${element(split("-", aws_vpc.main.id), 1)}"
  public_key = "${var.ssh_public_key}"
}
