# Generated by Otto, do not edit manually.
#
# Otto uses outputs as the method for transferring data from Terraform
# back into Otto that will be used for deploys, future infrastructure
# change, etc.
#
# Because of the importance of these values for Otto to function, care
# should be taken if these are modified.

output "region" {
    value = "${var.aws_region}"
}

output "datacenters" {
    value = "${lookup(var.aws_availability_zones, var.aws_region)}"
}

output "vpc_id" {
    value = "${aws_vpc.main.id}"
}

output "vpc_cidr" {
    value = "${aws_vpc.main.cidr_block}"
}

output "public_subnet_ids" {
    value = "${join(",",aws_subnet.public.*.id)}"
}

output "public_subnet_cidrs" {
    value = "${join(",",aws_subnet.public.*.cidr_block)}"
}

output "public_subnet_availability_zones" {
    value = "${join(",",aws_subnet.public.*.availability_zone)}"
}

output "key_name" {
    value = "${aws_key_pair.main.id}"
}

output "infra_id" {
    value = "${element(split("-", aws_vpc.main.id), 1)}"
}
